steps:
  # КРОК 0: Явна автентифікація за допомогою ключа з Secret Manager
  # Цей крок вирішує всі проблеми з дозволами
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret="REPORT_BOT_KEY" > /workspace/report-bot-key.json && gcloud auth activate-service-account report-bot@autoreportbot.iam.gserviceaccount.com --key-file=/workspace/report-bot-key.json'

  # Крок 1: Збираємо Docker-образ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/autoreportbot/my-app-repo/auto-report-generator:latest', '.']

  # Крок 2: Завантажуємо образ у наш репозиторій
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west1-docker.pkg.dev/autoreportbot/my-app-repo/auto-report-generator:latest']

  # Крок 3: Розгортаємо образ на Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'auto-report-generator'
      - '--image=europe-west1-docker.pkg.dev/autoreportbot/my-app-repo/auto-report-generator:latest'
      - '--region=europe-west1'
      - '--project=autoreportbot'
      - '--quiet'
      - '--set-secrets=GMAIL_TOKEN_JSON=GMAIL_TOKEN_JSON:latest,GMAIL_CREDENTIALS_JSON=GMAIL_CREDENTIALS_JSON:latest,GEMINI_API_KEY=GEMINI_API_KEY:latest'

# Вказуємо, який образ вважати фінальним артефактом збірки
images:
  - 'europe-west1-docker.pkg.dev/autoreportbot/my-app-repo/auto-report-generator:latest'

# Вказуємо, куди зберігати логи
logsBucket: 'gs://autoreportbot-build-logs'
options:
  logging: GCS_ONLY