name: Run Tests

on: 
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4 # Оновлено версію

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5 # Оновлено версію
        with:
          python-version: '3.12'

      # 3. Authenticate to Google Cloud (НОВИЙ КРОК)
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run unit tests with secrets (ОНОВЛЕНИЙ КРОК)
      - name: Run unit tests
        env:
          # Передаємо секрети як змінні середовища для тестів
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python -m unittest discover